=== pxtimes3/targettracker/schemas/bullet.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "array",
	"uniqueItemProperties": ["id"],
	"items": {
		"type": "object",
		"required": ["id", "name", "type", "manufacturer", "caliber", "caliberMm"],
		"properties": {
            "id": {
				"type": "string",
				"pattern": "^[a-z0-9.-]+$"
			},
            "manufacturer": {
				"type": "string",
				"minLength": 2
			},
			"name": {
				"type": "string",
				"minLength": 3,
				"maxLength": 256
			},
			"type": {
				"type": "string",
				"enum": ["centerfire", "rimfire", "shotgun", "airgun"]
			},
			"caliber": {
				"type": "number"
			},
			"caliberMm": {
				"type": "number"
			},
            "weight": {
                "type": "number",
                "minLength": 3,
                "maxLength": 24
            },
            "weightMetric": {
                "type": "number",
                "minLength": 3,
                "maxLength": 24
            },
            "sd": {
                "type": ["number", "null"],
                "minLength": 3,
                "maxLength": 24
            },
            "bc1": {
                "type": ["number", "null"],
                "minLength": 3,
                "maxLength": 24
            },
            "bc7": {
                "type": ["number", "null"],
                "minLength": 3,
                "maxLength": 24
            }
		},
		"additionalProperties": false
	}
}

=== pxtimes3/targettracker/src/bullets/hornady.json
[
  {
    "id": "hornady-varminatorexpress-224-69",
    "manufacturer": "Hornady",
    "name": "Varminator Express",
    "caliber": 0.224,
    "caliberMm": 5.6896,
    "weight": 69,
    "weightMetric": 4.47112,
    "sd": 0.123,
    "bc1": 0.11,
    "bc7": 0.22,
    "type": "centerfire"
  },
  {
    "id": "hornady-varminatorexpress-224-55",
    "manufacturer": "Hornady",
    "name": "Varminator Express",
    "caliber": 0.224,
    "caliberMm": 5.6896,
    "weight": 55,
    "weightMetric": 3.56394,
    "sd": 0.234,
    "bc1": 0.12,
    "bc7": 0.23,
    "type": "centerfire"
  },
  {
    "id": "hornady-varminatorexpress-224-40",
    "manufacturer": "Hornady",
    "name": "Varminator Express",
    "caliber": 0.224,
    "caliberMm": 5.6896,
    "weight": 40,
    "weightMetric": 2.59196,
    "sd": 0.345,
    "bc1": 0.13,
    "bc7": 0.24,
    "type": "centerfire"
  }
]
